[package]
name = "rust-paste-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
rand = "0.8.5"
rusqlite = "0.32.1"
serde = { version = "1.0.216", features = ["derive"] }
